### ISSUE TITLE
Compatibility with newer versions of ol

### ISSUE THREAD

**Issue by tpluscode** [pilattebe/ol-json-styles#1]
Hello. I found this repo which can be useful for [OL Web Components](https://github.com/openlayers-elements/openlayers-elements) I've been working on but I see a dependency on v6 of Open Layers. They have been releasing major versions frequently, now at v10

Do you think your package could be (made) compatible with any `ol >= 6`?

**Comment by pilattebe** [comment]
Hi, this library is currently a single function with 15 lines of code and no dependencies (except OL of course).
I think it should be trivial to make it compatible with newer versions if for any reason it should break.

Do you want to create a pull request ? Do you want a better understanding of the code ?

Note that I produced this code for a specific use case I had. I would advise against giving it any untrusted user input.

**Comment by tpluscode** [comment]
Well, I tried it with v8 and it just worked. You're right, the code is quite simple. 

That said, I found that I need a small change where `Style` is only created manually. Need to think about this

**Comment by pilattebe** [comment]
Could you clarify?

It is true that I only created `loadStyle`, where I initially intended on having a `dumpStyle` function to do the opposite of `loadStyle`. That said, the need for the reverse function never materialized in my case. It is true that a serializer would be a great addition to this de-serialization function to complete the library.

On a small note, I noticed that my latest changes were not pushed to npm. The version currently on the registry has a small bug where it doesn't handle offset arrays and anchor position for icons.

**Comment by tpluscode** [comment]
> Could you clarify?

The use case is that in plain HTML I can only set text attributes. I work on Web Components which wrap the Open Layers concepts, such as `ol-select` and to be able to set the `featureStyle` without JS you'd do something like

```html
<ol-select feature-style='{
  "fill": { "Fill": {
    "color": "rgba(255,255,255,0.4)"
  }},
  "stroke": { "Stroke": {
    "color": "#ffb15e",
    "width": 5
  }}
}'></ol-select>
```

This would translate to 

```js
const element = document.qerySelector('ol-select')

element.featureStyle = new Style({
  fill: new Fill({
    color: 'rgba(255,255,255,0.4)',
  }),
  stroke: new Stroke({
    color: '#ffb15e',
    width: 5,
  }),
})
```

So, the change I mentioned in my earlier comment is that I drop the top-level `Style` from the JSON, given the assumption that the attribute value represents the argument given to `new Style()` constructor and not style object as a whole

**Comment by tpluscode** [comment]
And to be honest, I'd simplify this one step further, removing the explicit `"Fill"` etc and instead picking the class based on the usage

```diff
<ol-select feature-style='{
- "fill": { "Fill": {
+ "fill": {
    "color": "rgba(255,255,255,0.4)"
-  }},
+ },
- "stroke": { "Stroke": {
+ "stroke": { 
    "color": "#ffb15e",
    "width": 5
- }}
+ }
}'></ol-select>
```

**Comment by pilattebe** [comment]
This would add complexity which I am not willing to introduce.

While it is true that sometimes `fill: Fill` is redundant, it is also redundant in the open layers code.
In many cases, there is no redundancy. For example `image: Circle`. Handling these cases differently would lead to complex code.

**Comment by tpluscode** [comment]
Gotcha, my simplistic view of a particular use case obscures other possible combinations

**Comment by pilattebe** [comment]
The Styles on the top allows the implementation to be recursive and to work with partial styles.

**Comment by tpluscode** [comment]
Well, I think that partial style are still possible in my modification but there is a limitation where you'd want `CircleStyle` as the root, right?

**Comment by pilattebe** [comment]
> Gotcha, my simplistic view of a particular use case obscures other possible combinations

But as I said, this is only made with 15 lines of code so feel free to adapt to your specific situation and copy it into your codebase.

**Comment by tpluscode** [comment]
I think I'm happy with your code. Would only relax the dependency.

**Comment by pilattebe** [comment]
> I think I'm happy with your code. Would only relax the dependency.

For some reason, I am locked out of NPM so I will not be able to push it right now to the repository but will add a GitHub action next week to do that automatically.

**Comment by tpluscode** [comment]
No worries. Thanks for merging

**Comment by pilattebe** [comment]
@tpluscode I pushed on npm sorry for the delay, I had my account locked
